const ACCOUNT_BOTS = [
    { seedId: 'qbot-1', username: 'WallRider_X', rating: 1200, country: 'US' },
    { seedId: 'qbot-2', username: 'pathfinder_99', rating: 1200, country: 'DE' },
    { seedId: 'qbot-3', username: 'QuoridorWolf', rating: 1200, country: 'PL' },
    { seedId: 'qbot-4', username: 'block_master', rating: 1200, country: 'GB' },
    { seedId: 'qbot-5', username: 'MazeLord7', rating: 1200, country: 'FR' },
    { seedId: 'qbot-6', username: 'xGhostRoute', rating: 1200, country: 'CA' },
];

const RANKED_BOTS = [
    { seedId: 'qbot-1', username: 'WallRider_X', rating: 1200, country: 'US' },
    { seedId: 'qbot-2', username: 'pathfinder_99', rating: 1200, country: 'DE' },
    { seedId: 'qbot-3', username: 'QuoridorWolf', rating: 1200, country: 'PL' },
    { seedId: 'qbot-4', username: 'block_master', rating: 1200, country: 'GB' },
    { seedId: 'qbot-5', username: 'MazeLord7', rating: 1200, country: 'FR' },
    { seedId: 'qbot-6', username: 'xGhostRoute', rating: 1200, country: 'CA' },
    { seedId: 'qbot-7', username: 'NovaRush', rating: 1200, country: 'RU' },
    { seedId: 'qbot-8', username: 'xDarkMaze', rating: 1200, country: 'BR' },
    { seedId: 'qbot-9', username: 'QuorKing42', rating: 1200, country: 'US' },
    { seedId: 'qbot-10', username: 'Pawn_Wall', rating: 1200, country: 'SE' },
    { seedId: 'qbot-11', username: 'FenceCrusher', rating: 1200, country: 'FI' },
    { seedId: 'qbot-12', username: 'RapidMover', rating: 1200, country: 'JP' },
    { seedId: 'qbot-13', username: 'StoneWall_9', rating: 1200, country: 'KR' },
    { seedId: 'qbot-14', username: 'MazeWalker', rating: 1200, country: 'NL' },
    { seedId: 'qbot-15', username: 'BlitzKnight', rating: 1200, country: 'UA' },
    { seedId: 'qbot-16', username: 'WallBreaker', rating: 1200, country: 'CL' },
    { seedId: 'qbot-17', username: 'xShadowFox', rating: 1200, country: 'TR' },
    { seedId: 'qbot-18', username: 'IronBarrier', rating: 1200, country: 'AU' },
    { seedId: 'qbot-19', username: 'FastLane_7', rating: 1200, country: 'ID' },
    { seedId: 'qbot-20', username: 'CrowMaze', rating: 1200, country: 'AR' },
];

const SOCIAL_BOTS = [
    { seedId: 'sbot-1', username: 'xShadow_77', rating: 1200, country: 'US' },
    { seedId: 'sbot-2', username: 'MegaKrot', rating: 1200, country: 'RU' },
    { seedId: 'sbot-3', username: 'ViperZ', rating: 1200, country: 'BR' },
    { seedId: 'sbot-4', username: 'neon_rat', rating: 1200, country: 'JP' },
    { seedId: 'sbot-5', username: 'GhostByte', rating: 1200, country: 'DE' },
    { seedId: 'sbot-6', username: 'TurboKat', rating: 1200, country: 'GB' },
    { seedId: 'sbot-7', username: 'CryptoKid', rating: 1200, country: 'US' },
    { seedId: 'sbot-8', username: 'sk8ter_pro', rating: 1200, country: 'FR' },
    { seedId: 'sbot-9', username: 'PixelHunter', rating: 1200, country: 'CA' },
    { seedId: 'sbot-10', username: 'noob2pro', rating: 1200, country: 'US' },
    { seedId: 'sbot-11', username: 'VelocityRun', rating: 1200, country: 'AU' },
    { seedId: 'sbot-12', username: 'raven_strike', rating: 1200, country: 'PL' },
    { seedId: 'sbot-13', username: 'coldSnipe', rating: 1200, country: 'FI' },
    { seedId: 'sbot-14', username: 'zapwire', rating: 1200, country: 'SE' },
    { seedId: 'sbot-15', username: 'Echo_Five', rating: 1200, country: 'GB' },
    { seedId: 'sbot-16', username: 'grizzly_gm', rating: 1200, country: 'RU' },
    { seedId: 'sbot-17', username: 'duskrunner', rating: 1200, country: 'US' },
    { seedId: 'sbot-18', username: 'IronClad88', rating: 1200, country: 'DE' },
    { seedId: 'sbot-19', username: 'sneaky_pete', rating: 1200, country: 'US' },
    { seedId: 'sbot-20', username: 'StarFrag', rating: 1200, country: 'NL' },
    { seedId: 'sbot-21', username: 'mr_nobody_', rating: 1200, country: 'GB' },
    { seedId: 'sbot-22', username: 'quickdraw_k', rating: 1200, country: 'US' },
    { seedId: 'sbot-23', username: 'Zeph_nine', rating: 1200, country: 'NZ' },
    { seedId: 'sbot-24', username: 'CrimsonBolt', rating: 1200, country: 'BR' },
    { seedId: 'sbot-25', username: 'ace_of_clubs', rating: 1200, country: 'GB' },
    { seedId: 'sbot-26', username: 'TitanGrip', rating: 1200, country: 'US' },
    { seedId: 'sbot-27', username: 'softstep', rating: 1200, country: 'JP' },
    { seedId: 'sbot-28', username: 'drifter99', rating: 1200, country: 'AU' },
    { seedId: 'sbot-29', username: 'blue_apex', rating: 1200, country: 'US' },
    { seedId: 'sbot-30', username: 'SolarWind7', rating: 1200, country: 'ES' },
    { seedId: 'sbot-31', username: 'punchy_mc', rating: 1200, country: 'IE' },
    { seedId: 'sbot-32', username: 'Hollowpoint', rating: 1200, country: 'US' },
    { seedId: 'sbot-33', username: 'ZeroKelvin', rating: 1200, country: 'NO' },
    { seedId: 'sbot-34', username: 'micro_beast', rating: 1200, country: 'KR' },
    { seedId: 'sbot-35', username: 'swift_edge', rating: 1200, country: 'DE' },
    { seedId: 'sbot-36', username: 'vapor_99', rating: 1200, country: 'US' },
    { seedId: 'sbot-37', username: 'IceBreaker', rating: 1200, country: 'CA' },
    { seedId: 'sbot-38', username: 'lostpacket', rating: 1200, country: 'GB' },
    { seedId: 'sbot-39', username: 'str1der', rating: 1200, country: 'US' },
    { seedId: 'sbot-40', username: 'DeltaForce5', rating: 1200, country: 'RU' },
    { seedId: 'sbot-41', username: 'toxic_cloud', rating: 1200, country: 'PL' },
    { seedId: 'sbot-42', username: 'MadHawke', rating: 1200, country: 'US' },
    { seedId: 'sbot-43', username: 'FrostFang', rating: 1200, country: 'SE' },
    { seedId: 'sbot-44', username: 'qwerty_kill', rating: 1200, country: 'GB' },
    { seedId: 'sbot-45', username: 'BlackNova', rating: 1200, country: 'US' },
    { seedId: 'sbot-46', username: 'hyperlink_99', rating: 1200, country: 'DE' },
    { seedId: 'sbot-47', username: 'camo_dog', rating: 1200, country: 'AU' },
    { seedId: 'sbot-48', username: 'AbyssWalker', rating: 1200, country: 'US' },
    { seedId: 'sbot-49', username: 'Ripcode', rating: 1200, country: 'BR' },
    { seedId: 'sbot-50', username: 'kz_shark', rating: 1200, country: 'RU' },
    { seedId: 'sbot-51', username: 'FastTrack9', rating: 1200, country: 'ZA' },
    { seedId: 'sbot-52', username: 'SilverLance', rating: 1200, country: 'GB' },
    { seedId: 'sbot-53', username: 'no_scope_k', rating: 1200, country: 'US' },
    { seedId: 'sbot-54', username: 'tempest_z', rating: 1200, country: 'AU' },
    { seedId: 'sbot-55', username: 'Ratchet7', rating: 1200, country: 'US' },
    { seedId: 'sbot-56', username: 'CrystalByte', rating: 1200, country: 'JP' },
    { seedId: 'sbot-57', username: 'frag_lord', rating: 1200, country: 'US' },
    { seedId: 'sbot-58', username: 'sly_rogue', rating: 1200, country: 'IE' },
    { seedId: 'sbot-59', username: 'bravo_kilo', rating: 1200, country: 'GB' },
    { seedId: 'sbot-60', username: 'Flatline', rating: 1200, country: 'US' },
    { seedId: 'sbot-61', username: 'quickshift', rating: 1200, country: 'DE' },
    { seedId: 'sbot-62', username: 'dust_devil', rating: 1200, country: 'US' },
    { seedId: 'sbot-63', username: 'ArcLight', rating: 1200, country: 'CA' },
    { seedId: 'sbot-64', username: 'SkyPirate', rating: 1200, country: 'GB' },
    { seedId: 'sbot-65', username: 'zero_lag', rating: 1200, country: 'JP' },
    { seedId: 'sbot-66', username: 'WildSurge', rating: 1200, country: 'US' },
    { seedId: 'sbot-67', username: 'nullzone_mc', rating: 1200, country: 'RU' },
    { seedId: 'sbot-68', username: 'DropKick9', rating: 1200, country: 'AU' },
    { seedId: 'sbot-69', username: 'blur_agent', rating: 1200, country: 'US' },
    { seedId: 'sbot-70', username: 'BinaryFrog', rating: 1200, country: 'DE' },
    { seedId: 'sbot-71', username: 'casual_nuke', rating: 1200, country: 'US' },
    { seedId: 'sbot-72', username: 'thunder_carrot', rating: 1200, country: 'GB' },
    { seedId: 'sbot-73', username: 'PebbleShot', rating: 1200, country: 'CA' },
    { seedId: 'sbot-74', username: 'iron_biscuit', rating: 1200, country: 'IE' },
    { seedId: 'sbot-75', username: 'SleepySniper', rating: 1200, country: 'US' },
    { seedId: 'sbot-76', username: 'MarbleRun', rating: 1200, country: 'SE' },
    { seedId: 'sbot-77', username: 'BumbleRocket', rating: 1200, country: 'GB' },
    { seedId: 'sbot-78', username: 'noodle_arms', rating: 1200, country: 'US' },
    { seedId: 'sbot-79', username: 'QuickPickle', rating: 1200, country: 'NZ' },
    { seedId: 'sbot-80', username: 'rusted_bolt', rating: 1200, country: 'DE' },
    { seedId: 'sbot-81', username: 'SocketWrench', rating: 1200, country: 'US' },
    { seedId: 'sbot-82', username: 'fuzzy_logic', rating: 1200, country: 'GB' },
    { seedId: 'sbot-83', username: 'BouncingBomb', rating: 1200, country: 'AU' },
    { seedId: 'sbot-84', username: 'dry_run99', rating: 1200, country: 'US' },
    { seedId: 'sbot-85', username: 'SteelPenguin', rating: 1200, country: 'NO' },
    { seedId: 'sbot-86', username: 'morning_frag', rating: 1200, country: 'DE' },
    { seedId: 'sbot-87', username: 'TankerFish', rating: 1200, country: 'US' },
    { seedId: 'sbot-88', username: 'loose_cannon', rating: 1200, country: 'GB' },
    { seedId: 'sbot-89', username: 'GravelPit', rating: 1200, country: 'FI' },
    { seedId: 'sbot-90', username: 'spring_loaded', rating: 1200, country: 'US' },
    { seedId: 'sbot-91', username: 'WrenchMonkey', rating: 1200, country: 'CA' },
    { seedId: 'sbot-92', username: 'flat_white', rating: 1200, country: 'AU' },
    { seedId: 'sbot-93', username: 'CopperKnife', rating: 1200, country: 'US' },
    { seedId: 'sbot-94', username: 'heavy_rotation', rating: 1200, country: 'BR' },
    { seedId: 'sbot-95', username: 'SprintCycle', rating: 1200, country: 'GB' },
    { seedId: 'sbot-96', username: 'burnt_toast9', rating: 1200, country: 'US' },
    { seedId: 'sbot-97', username: 'MuddyBoots', rating: 1200, country: 'IE' },
    { seedId: 'sbot-98', username: 'couch_warrior', rating: 1200, country: 'US' },
    { seedId: 'sbot-99', username: 'RubberBullet', rating: 1200, country: 'ZA' },
    { seedId: 'sbot-100', username: 'TickTock88', rating: 1200, country: 'GB' },
];

const GUEST_BOTS = [
    { name: 'Guest-a1b2', rating: 850, difficulty: 'easy' },
    { name: 'Guest-c3d4', rating: 920, difficulty: 'easy' },
    { name: 'Guest-e5f6', rating: 1000, difficulty: 'medium' },
    { name: 'Guest-g7h8', rating: 1080, difficulty: 'medium' },
    { name: 'Guest-i9j0', rating: 1150, difficulty: 'medium' },
    { name: 'Guest-k1l2', rating: 880, difficulty: 'easy' },
    { name: 'Guest-m3n4', rating: 960, difficulty: 'easy' },
    { name: 'Guest-o5p6', rating: 1040, difficulty: 'medium' },
    { name: 'Guest-q7r8', rating: 1120, difficulty: 'medium' },
    { name: 'Guest-s9t0', rating: 1200, difficulty: 'medium' },
];

const ALL_BOTS = [...RANKED_BOTS, ...SOCIAL_BOTS];

function randomGuestBot() {
    const hex = Math.random().toString(16).substring(2, 6);
    const rating = 800 + Math.floor(Math.random() * 500);
    const difficulties = ['easy', 'easy', 'medium', 'medium', 'medium'];
    const difficulty = difficulties[Math.floor(Math.random() * difficulties.length)];
    return { name: `Guest-${hex}`, rating, difficulty };
}

module.exports = { ACCOUNT_BOTS, RANKED_BOTS, SOCIAL_BOTS, ALL_BOTS, GUEST_BOTS, randomGuestBot };
