/**
 * Quoridor local AI worker — engine v1.
 *
 * Runs the same quoridor-engine/engines/v1 as the server bots and the arena. The bundle is generated by
 * src/core/ai-v1-bundle.js and published as /js/ai-v1.js; it resolves the rules to the global `Shared`
 * that /shared.js installs, so import order matters: rules first, engine second.
 */
importScripts('/shared.js');
importScripts('/js/ai-v1.js');

/**
 * One engine per local game.
 *
 * Not one per worker: the engine keeps a transposition table whose key omits the player index, so a
 * single instance shared across games (or across seats) lets stored scores be read back as if they
 * belonged to the side being searched. A worker outlives many games — rematches, "play again" — so the
 * instance is replaced on every new game rather than reused.
 */
let engine = null;

function createEngine(difficulty) {
    return AiV1.createEngineV1({
        // Depth-only tiers: a random move would reintroduce exactly the repetition loops the engine
        // now bans, which is why the arena runs every tier with randomness disabled.
        easyRandomP: 0,
        maxDepth: AiV1.difficultyToMaxDepth(difficulty),
    });
}

function log(...args) {
    const msg = args.map(a => (typeof a === 'object' ? JSON.stringify(a) : String(a))).join(' ');
    postMessage({ type: 'debug', message: msg });
}

onmessage = function (e) {
    const msg = e.data || {};

    if (msg.type === 'newGame') {
        engine = createEngine(msg.difficulty);
        postMessage({ type: 'ready', maxDepth: AiV1.difficultyToMaxDepth(msg.difficulty) });
        return;
    }

    if (msg.type === 'endGame') {
        engine = null;
        return;
    }

    try {
        const { state, botIdx, difficulty } = msg;

        // Lazily built so a think() that arrives without a newGame (older tab, restored game) still
        // works instead of throwing.
        if (!engine) engine = createEngine(difficulty || 'medium');

        const startedAt = Date.now();
        const result = engine.think(state, {
            player: botIdx,
            maxDepth: AiV1.difficultyToMaxDepth(difficulty),
            easyRandomP: 0,
        });

        if (!result || !result.move) throw new Error('engine returned no move');

        postMessage({
            type: 'move',
            move: result.move,
            depth: result.depth,
            nodes: result.nodes,
            ms: Date.now() - startedAt,
        });
    } catch (err) {
        console.error('[AI-WORKER] think failed:', err);
        postMessage({ type: 'error', message: String((err && err.message) || err) });
    }
};
