/**
 * Quoridor local AI worker — engine v3.
 *
 * Runs the same quoridor-engine/engines/v3 as the server bots and the arena. The bundle is generated by
 * src/core/ai-v1-bundle.js and published as /js/ai-v1.js (historical URL); it resolves the rules to the
 * global `Shared` that /shared.js installs, so import order matters: rules first, engine second. The
 * ?v= matches the tag in index.html — without it this import is served straight from the 4h cache and
 * keeps the previous engine.
 */
importScripts('/shared.js');
importScripts('/js/ai-v1.js?v=1.3.2');

/**
 * One engine per local game.
 *
 * Not one per worker: the engine keeps a transposition table whose key omits the player index, so a
 * single instance shared across games (or across seats) lets stored scores be read back as if they
 * belonged to the side being searched. A worker outlives many games — rematches, "play again" — so the
 * instance is replaced on every new game rather than reused.
 *
 * A fresh random seed per game is also what makes the openings varied: the engine is deterministic, so
 * the same seed would replay the same line. personality(botId) adds a per-bot style on top of it.
 */
let engine = null;
let botId = null;

function randomSeed() {
    if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
        const a = new Uint32Array(1);
        crypto.getRandomValues(a);
        return a[0] & 0x7fffffff;
    }
    return Math.floor(Math.random() * 0x7fffffff);
}

function createEngine(difficulty, id) {
    const p = (id && AiV1.personality) ? AiV1.personality(id) : null;
    return AiV1.createEngineV1({
        seed: randomSeed(),
        difficulty: difficulty,
        maxDepth: AiV1.difficultyToMaxDepth(difficulty),
        weights: p ? p.weights : undefined,
        variety: (AiV1.varietyForDifficulty ? AiV1.varietyForDifficulty(difficulty) : AiV1.VARIETY_DEFAULT),
        archetype: p ? { names: p.archetypes } : undefined,
    });
}

function log(...args) {
    const msg = args.map(a => (typeof a === 'object' ? JSON.stringify(a) : String(a))).join(' ');
    postMessage({ type: 'debug', message: msg });
}

onmessage = function (e) {
    const msg = e.data || {};

    if (msg.type === 'newGame') {
        botId = msg.botId || ('local-' + Date.now().toString(36));
        engine = createEngine(msg.difficulty, botId);
        postMessage({ type: 'ready', maxDepth: AiV1.difficultyToMaxDepth(msg.difficulty) });
        return;
    }

    if (msg.type === 'endGame') {
        engine = null;
        return;
    }

    try {
        const { state, botIdx, difficulty } = msg;

        // Lazily built so a think() that arrives without a newGame (older tab, restored game) still
        // works instead of throwing.
        if (!engine) engine = createEngine(difficulty || 'medium', botId || msg.botId);

        const startedAt = Date.now();
        const result = engine.think(state, {
            player: botIdx,
            maxDepth: AiV1.difficultyToMaxDepth(difficulty),
        });

        if (!result || !result.move) throw new Error('engine returned no move');

        postMessage({
            type: 'move',
            move: result.move,
            depth: result.depth,
            nodes: result.nodes,
            ms: Date.now() - startedAt,
        });
    } catch (err) {
        console.error('[AI-WORKER] think failed:', err);
        postMessage({ type: 'error', message: String((err && err.message) || err) });
    }
};
